version = 1

[[cities]]
slug = "san-francisco"
address = "San Francisco, USA"
displayName = "San Francisco"
mapCoordinates = [ 0, 0 ]

[[cities.popos]]
name = "Transamerica Redwood Park"
imageName = "sf_transamerica-pyramid.jpg"
openingHours = "Mon - Fri 7am - 5:30pm"
description = "600 Montgomery St."
mapCoordinates = [ 37.795222, -122.402332 ]

[[cities.popos]]
name = "Empire Park"
openingHours = "Mon - Fri 7am - 5:30pm"
description = "648 Commercial St."
mapCoordinates = [ 37.794269, -122.403713 ]

[[cities.popos]]
name = "Embarcadero Center"
openingHours = "The first of the three open spaces here is the con..."
description = "400-492 Commercial St."
mapCoordinates = [ 37.794425, -122.400239 ]

[[cities.popos]]
name = "343 Sansome"
openingHours = "Mon - Fri 10am - 5pm"
description = "343 Sansome St."
mapCoordinates = [ 37.793616, -122.401572 ]

[[cities.popos]]
name = "555 California"
openingHours = "Open at all times."
description = "555 California St."
mapCoordinates = [ 37.79258, -122.403518 ]

[[cities.popos]]
name = "150 California"
openingHours = "Mon - Fri 9am - 6pm"
description = "150 California St."
mapCoordinates = [ 37.793673, -122.398464 ]

[[cities.popos]]
name = "101 California"
openingHours = "Open at all times."
description = "101 California St."
mapCoordinates = [ 37.79304, -122.398032 ]

[[cities.popos]]
name = "100 Pine"
openingHours = "10am - 6pm"
description = "100 Pine St."
mapCoordinates = [ 37.792641, -122.39897 ]

[[cities.popos]]
name = "One Bush Plaza"
openingHours = "Open at all times."
description = "1 Bush St."
mapCoordinates = [ 37.791092, -122.400122 ]

[[cities.popos]]
name = "Citigroup Center"
openingHours = "Open during business hours."
description = "1 Sansome St."
mapCoordinates = [ 37.790485, -122.40094 ]

[[cities.popos]]
name = "Crocker Galleria"
openingHours = "Mon - Sat 10am - 6pm"
description = "50 Post St."
mapCoordinates = [ 37.789531, -122.403041 ]

[[cities.popos]]
name = "Market Center"
openingHours = "The beautifully landscaped urban garden takes up t..."
description = "555–575 Market St."
mapCoordinates = [ 37.790066, -122.399944 ]

[[cities.popos]]
name = "One Kearny"
openingHours = "Mon - Fri 10am -5pm"
description = "23 Geary St."
mapCoordinates = [ 37.787707, -122.403853 ]

[[cities.popos]]
name = "456 Montgomery"
openingHours = "Some seating has been provided at the sidewalk lev..."
description = "456 Montgomery St."
mapCoordinates = [ 37.793473, -122.402667 ]

[[cities.popos]]
name = "425 Market"
openingHours = "Open at all times."
description = "425 Market St."
mapCoordinates = [ 37.791121, -122.398125 ]

[[cities.popos]]
name = "50 Beale"
openingHours = "Open at all times."
description = "50 Beale St."
mapCoordinates = [ 37.791239, -122.396457 ]

[[cities.popos]]
name = "201 Mission"
openingHours = "Open at all times."
description = "201 Mission St."
mapCoordinates = [ 37.791034, -122.394768 ]

[[cities.popos]]
name = "123 Mission"
openingHours = "Open at all times."
description = "123 Mission St."
mapCoordinates = [ 37.791882, -122.394339 ]

[[cities.popos]]
name = "135 Main"
openingHours = "Open during office hours."
description = "135 Main St."
mapCoordinates = [ 37.791459, -122.394241 ]

[[cities.popos]]
name = "100 First"
openingHours = "Open during daylight hours."
description = "100 First St."
mapCoordinates = [ 37.789488, -122.397593 ]

[[cities.popos]]
name = "Ecker Square"
openingHours = "Open at all times."
description = "25 Jessie St."
mapCoordinates = [ 37.789658, -122.3987 ]

[[cities.popos]]
name = "55 Second"
openingHours = "Mon - Fri 8am - 6pm"
description = "55 2nd St."
mapCoordinates = [ 37.78879, -122.400422 ]

[[cities.popos]]
name = "560 Mission"
openingHours = "Open at all times."
description = "560 Mission St."
mapCoordinates = [ 37.788709, -122.399154 ]

[[cities.popos]]
name = "555 Mission"
openingHours = "Open at all times."
description = "555 Mission St."
mapCoordinates = [ 37.788601, -122.398674 ]

[[cities.popos]]
name = "101 Second"
openingHours = "Mon - Fri 8am - 6pm"
description = "101 2nd St."
mapCoordinates = [ 37.78808, -122.399144 ]

[[cities.popos]]
name = "Marathon Plaza"
openingHours = "Open at all times."
description = "303 2nd St."
mapCoordinates = [ 37.785292, -122.395566 ]

[[cities.popos]]
name = "Millenium Tower Atrium"
openingHours = "8am - 6pm"
description = "301 Mission St."
mapCoordinates = [ 37.790582, -122.396142 ]

[[cities.popos]]
name = "222 Second"
openingHours = "Mon - Fri 8am - 6pm"
description = "222 2nd St."
mapCoordinates = [ 37.78632, -122.398235 ]

[[cities.popos]]
name = "Sky Terrace"
openingHours = "Open during business hours."
description = "825 Market St."
mapCoordinates = [ 37.784803, -122.406071 ]

[[cities.popos]]
name = "543 Howard"
openingHours = "Mon - Fri 8am - 5pm"
description = "543 Howard St."
mapCoordinates = [ 37.787594, -122.396631 ]

[[cities.popos]]
name = "14 Fremont"
openingHours = "Open at all times."
description = "14 Fremont St."
mapCoordinates = [ 37.791454, -122.398215 ]

[[cities.popos]]
name = "Foundry Square I"
openingHours = "Open at all times."
description = "400 Howard St."
mapCoordinates = [ 37.789137, -122.3958 ]

[[cities.popos]]
name = "Foundry Square II"
openingHours = "Open at all times."
description = "405 Howard St."
mapCoordinates = [ 37.788609, -122.395376 ]

[[cities.popos]]
name = "Foundry Square III"
openingHours = "Plaza is open at all times. Indoor Park, Mon - Fri 8am - 6pm"
description = "505 Howard St."
mapCoordinates = [ 37.788264, -122.39608 ]

[[cities.popos]]
name = "Foundry Square IV"
openingHours = "Open at all times."
description = "500 Howard St."
mapCoordinates = [ 37.788433, -122.396689 ]

[[cities.popos]]
name = "160 Spear"
openingHours = "Open at all times."
description = "160 Spear St."
mapCoordinates = [ 37.791575, -122.39339 ]

[[cities.popos]]
name = "201 Spear"
openingHours = "Open at all times."
description = "201 Spear St."
mapCoordinates = [ 37.791185, -122.391791 ]

[[cities.popos]]
name = "2 Folsom"
openingHours = "Open at all times."
description = "2 Folsom St."
mapCoordinates = [ 37.790663, -122.390742 ]

[[cities.popos]]
name = "235 Main"
openingHours = "Mon - Fri 8am - 6pm"
description = "235 Main St."
mapCoordinates = [ 37.790287, -122.392876 ]

[[cities.popos]]
name = "The Clancy"
openingHours = "Outdoor public sitting area is open at all times. Indoor garden, Mon - Fri 8am - 6pm."
description = "299 2nd St."
mapCoordinates = [ 37.785961, -122.396817 ]

[[cities.popos]]
name = "Shaw Alley"
openingHours = "Mon - Fri 8am - 6pm"
description = "535 Mission St."
mapCoordinates = [ 37.788856, -122.398106 ]

[[cities.popos]]
name = "Golden Gate University"
openingHours = "Open at all times."
description = "536 Mission St."
mapCoordinates = [ 37.789249, -122.398893 ]

[[cities.popos]]
name = "71 Stevenson"
openingHours = "Open at all times."
description = "71 Stevenson St."
mapCoordinates = [ 37.789373, -122.399666 ]

[[cities.popos]]
name = "49 Stevenson"
openingHours = "Open at all times."
description = "49 Stevenson St."
mapCoordinates = [ 37.789736, -122.399352 ]

[[cities.popos]]
name = "611 Folsom"
openingHours = "Open at all times."
description = "611 Folsom St."
mapCoordinates = [ 37.78498, -122.396536 ]

[[cities]]
slug = "boston"
displayName = "Boston"
mapCoordinates = [ 0, 0 ]

[[cities.popos]]
name = "Test Popo 3"
openingHours = "8am - 9pm Mondays"
mapCoordinates = [ 1, 1 ]
description = "It has some cool stuff. Might be hard to find!"

[[cities.popos]]
name = "Test Popo 4"
openingHours = "81am - 29pm Fridays"
mapCoordinates = [ 1, 1 ]
description = "It has no cool stuff at all. Easy to find!"
